// <auto-generated />
using System;
using Blog.Repository.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blog.Api.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20220316095821_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blog.Entities.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 788, DateTimeKind.Utc).AddTicks(6736));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Thumbnail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasDefaultValue("default.jpg");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 788, DateTimeKind.Utc).AddTicks(6965));

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("507462a3-5639-4573-b7d9-306d560a7ca8"),
                            CategoryId = new Guid("5533e9a6-186f-4a3d-9ef4-63a2f7c02eb2"),
                            CommentCount = 2,
                            Content = "ilk makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(322),
                            Description = "ilk makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(337),
                            Thumbnail = "default.jpg",
                            Title = "ilk makale",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(331),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            ViewsCount = 33
                        },
                        new
                        {
                            Id = new Guid("15cd7fe9-3d73-4028-b3f1-0e8a09112570"),
                            CategoryId = new Guid("5533e9a6-186f-4a3d-9ef4-63a2f7c02eb2"),
                            CommentCount = 3,
                            Content = "ikinci makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(342),
                            Description = "ikinci makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(347),
                            Thumbnail = "default.jpg",
                            Title = "ikinci makale",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(344),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            ViewsCount = 25
                        },
                        new
                        {
                            Id = new Guid("d1267b3b-c386-4481-804b-17c38c28d122"),
                            CategoryId = new Guid("1bbc4e68-3e73-4f11-bd09-11ba71b5b582"),
                            CommentCount = 1,
                            Content = "üçüncü makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(351),
                            Description = "üçüncü makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(355),
                            Thumbnail = "default.jpg",
                            Title = "üçüncü makale",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(353),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            ViewsCount = 11
                        },
                        new
                        {
                            Id = new Guid("ddb5c34f-518c-4189-ae3a-fe9103558500"),
                            CategoryId = new Guid("1bbc4e68-3e73-4f11-bd09-11ba71b5b582"),
                            CommentCount = 5,
                            Content = "dördüncü makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(358),
                            Description = "dördüncü makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(363),
                            Thumbnail = "default.jpg",
                            Title = "dördüncü makale",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(360),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            ViewsCount = 10
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(1002));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MainCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(1230));

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("MainCategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5533e9a6-186f-4a3d-9ef4-63a2f7c02eb2"),
                            CategoryName = "Yazılım",
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(3066),
                            Description = "Yazılım kategorisine ait makaleler",
                            IsActive = true,
                            MainCategoryId = new Guid("eec3877e-de06-47a5-9f29-764cebf7851d"),
                            TagName = "YZL",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(3075)
                        },
                        new
                        {
                            Id = new Guid("1bbc4e68-3e73-4f11-bd09-11ba71b5b582"),
                            CategoryName = "Sinema",
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(3081),
                            Description = "Sinema kategorisine ait makaleler",
                            IsActive = true,
                            MainCategoryId = new Guid("11070708-1c30-4967-9bcf-433e703f348a"),
                            TagName = "SİN",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(3082)
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(6017));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(6296));

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8d2fc77-9c77-48fe-9e7b-4f47c34fe27e"),
                            ArticleId = new Guid("507462a3-5639-4573-b7d9-306d560a7ca8"),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(8955),
                            IsActive = true,
                            Text = "örnek yorum 1",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(8964),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        },
                        new
                        {
                            Id = new Guid("e8acb53c-0f5d-44c6-bc2d-14f2afce41c7"),
                            ArticleId = new Guid("15cd7fe9-3d73-4028-b3f1-0e8a09112570"),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(8970),
                            IsActive = true,
                            Text = "örnek yorum 3",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(8971),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c")
                        },
                        new
                        {
                            Id = new Guid("fcda26c7-2469-415f-b2bf-7b2571c11e4a"),
                            ArticleId = new Guid("d1267b3b-c386-4481-804b-17c38c28d122"),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(8975),
                            IsActive = true,
                            Text = "örnek yorum 2",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(8977),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.FollowedAuthors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("FollowedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(3412));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSettingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSettingId");

                    b.ToTable("FollowedAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cd06ada-c8ce-4d70-9764-d7fe138bdd9c"),
                            FollowedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(4738),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            UserSettingId = new Guid("8ff845a2-ad00-4158-8b4a-061a5764c789")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.FollowersAuthors", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("FollowedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(5287));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserSettingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSettingId");

                    b.ToTable("FollowersAuthors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a07a6456-3576-48ad-8914-1cd5c1152904"),
                            FollowedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(6499),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            UserSettingId = new Guid("8ff845a2-ad00-4158-8b4a-061a5764c789")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.MainCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(9497));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MainCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(9717));

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryName")
                        .IsUnique();

                    b.ToTable("MainCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eec3877e-de06-47a5-9f29-764cebf7851d"),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(359),
                            IsActive = true,
                            MainCategoryName = "Bilim",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(366)
                        },
                        new
                        {
                            Id = new Guid("11070708-1c30-4967-9bcf-433e703f348a"),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(369),
                            IsActive = true,
                            MainCategoryName = "Kültür",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(370)
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(3738));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(3917));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            BirthDate = new DateTime(1995, 12, 27, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(5395),
                            Email = "necil@necil.com",
                            Gender = true,
                            IsActive = true,
                            NickName = "necilcakmak",
                            Password = "$2a$11$wnQMJKF1vC6fAxs5IDaM1.5S3oMG.gEQMhON0bHUl5UQfe8v1AwIK",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(5403),
                            UserName = "Necil",
                            UserSurname = "Çakmak"
                        },
                        new
                        {
                            Id = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            BirthDate = new DateTime(1990, 11, 17, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(5494),
                            Email = "ömer@ömer.com",
                            Gender = false,
                            IsActive = true,
                            NickName = "ömergürsoy",
                            Password = "$2a$11$uNx/XA0odP6BAp8xKqtkausOYVPqmGNmq1GYK/y0E6OgQNb/7XIfC",
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 789, DateTimeKind.Utc).AddTicks(5497),
                            UserName = "Ömer",
                            UserSurname = "Gürsoy"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(931));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("NewBlog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ReceiveMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(1130));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff845a2-ad00-4158-8b4a-061a5764c789"),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(2819),
                            IsActive = true,
                            IsApproved = true,
                            NewBlog = true,
                            ReceiveMail = true,
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(2828),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        },
                        new
                        {
                            Id = new Guid("e88c8860-4b9a-4736-9ed3-5cf23a75a86b"),
                            CreatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(2835),
                            IsActive = true,
                            IsApproved = false,
                            NewBlog = true,
                            ReceiveMail = true,
                            UpdatedDate = new DateTime(2022, 3, 16, 9, 58, 20, 790, DateTimeKind.Utc).AddTicks(2837),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.Article", b =>
                {
                    b.HasOne("Blog.Entities.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Category", b =>
                {
                    b.HasOne("Blog.Entities.Entities.MainCategory", "MainCategory")
                        .WithMany("Categories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Comment", b =>
                {
                    b.HasOne("Blog.Entities.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.FollowedAuthors", b =>
                {
                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Entities.UserSetting", "UserSetting")
                        .WithMany("FollowedAuthors")
                        .HasForeignKey("UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("Blog.Entities.Entities.FollowersAuthors", b =>
                {
                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Entities.UserSetting", "UserSetting")
                        .WithMany("FollowersAuthors")
                        .HasForeignKey("UserSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserSetting", b =>
                {
                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("Blog.Entities.Entities.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Blog.Entities.Entities.MainCategory", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Blog.Entities.Entities.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("UserSetting")
                        .IsRequired();
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserSetting", b =>
                {
                    b.Navigation("FollowedAuthors");

                    b.Navigation("FollowersAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
