// <auto-generated />
using System;
using Blog.Repository.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blog.Api.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blog.Entities.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 564, DateTimeKind.Utc).AddTicks(6943));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Thumbnail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasDefaultValue("default.jpg");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 564, DateTimeKind.Utc).AddTicks(7174));

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.Property<int>("ViewsCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("507462a3-5639-4573-b7d9-306d560a7ca8"),
                            CategoryId = new Guid("5533e9a6-186f-4a3d-9ef4-63a2f7c02eb2"),
                            CommentCount = 2,
                            Content = "ilk makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(342),
                            Description = "ilk makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(354),
                            Thumbnail = "default.jpg",
                            Title = "ilk makale",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(350),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            ViewsCount = 33
                        },
                        new
                        {
                            Id = new Guid("15cd7fe9-3d73-4028-b3f1-0e8a09112570"),
                            CategoryId = new Guid("5533e9a6-186f-4a3d-9ef4-63a2f7c02eb2"),
                            CommentCount = 3,
                            Content = "ikinci makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(359),
                            Description = "ikinci makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(364),
                            Thumbnail = "default.jpg",
                            Title = "ikinci makale",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(360),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            ViewsCount = 25
                        },
                        new
                        {
                            Id = new Guid("d1267b3b-c386-4481-804b-17c38c28d122"),
                            CategoryId = new Guid("1bbc4e68-3e73-4f11-bd09-11ba71b5b582"),
                            CommentCount = 1,
                            Content = "üçüncü makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(368),
                            Description = "üçüncü makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(372),
                            Thumbnail = "default.jpg",
                            Title = "üçüncü makale",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(369),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            ViewsCount = 11
                        },
                        new
                        {
                            Id = new Guid("ddb5c34f-518c-4189-ae3a-fe9103558500"),
                            CategoryId = new Guid("1bbc4e68-3e73-4f11-bd09-11ba71b5b582"),
                            CommentCount = 5,
                            Content = "dördüncü makalenin içeriği",
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(376),
                            Description = "dördüncü makale açıklaması",
                            IsActive = true,
                            PublishedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(380),
                            Thumbnail = "default.jpg",
                            Title = "dördüncü makale",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(377),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            ViewsCount = 10
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(1082));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MainCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(1278));

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("MainCategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5533e9a6-186f-4a3d-9ef4-63a2f7c02eb2"),
                            CategoryName = "Yazılım",
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(3203),
                            Description = "Yazılım kategorisine ait makaleler",
                            IsActive = true,
                            MainCategoryId = new Guid("eec3877e-de06-47a5-9f29-764cebf7851d"),
                            TagName = "YZL",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(3211)
                        },
                        new
                        {
                            Id = new Guid("1bbc4e68-3e73-4f11-bd09-11ba71b5b582"),
                            CategoryName = "Sinema",
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(3217),
                            Description = "Sinema kategorisine ait makaleler",
                            IsActive = true,
                            MainCategoryId = new Guid("11070708-1c30-4967-9bcf-433e703f348a"),
                            TagName = "SİN",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(3218)
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(5982));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(6179));

                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8d2fc77-9c77-48fe-9e7b-4f47c34fe27e"),
                            ArticleId = new Guid("507462a3-5639-4573-b7d9-306d560a7ca8"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(8866),
                            IsActive = true,
                            Text = "örnek yorum 1",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(8874),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        },
                        new
                        {
                            Id = new Guid("e8acb53c-0f5d-44c6-bc2d-14f2afce41c7"),
                            ArticleId = new Guid("15cd7fe9-3d73-4028-b3f1-0e8a09112570"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(8880),
                            IsActive = true,
                            Text = "örnek yorum 3",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(8881),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c")
                        },
                        new
                        {
                            Id = new Guid("fcda26c7-2469-415f-b2bf-7b2571c11e4a"),
                            ArticleId = new Guid("d1267b3b-c386-4481-804b-17c38c28d122"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(8885),
                            IsActive = true,
                            Text = "örnek yorum 2",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(8887),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.MainCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(9392));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("MainCategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(9562));

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryName")
                        .IsUnique();

                    b.ToTable("MainCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eec3877e-de06-47a5-9f29-764cebf7851d"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(228),
                            IsActive = true,
                            MainCategoryName = "Bilim",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(234)
                        },
                        new
                        {
                            Id = new Guid("11070708-1c30-4967-9bcf-433e703f348a"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(237),
                            IsActive = true,
                            MainCategoryName = "Kültür",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(239)
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(3721));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(3931));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NickName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            BirthDate = new DateTime(1995, 12, 27, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(5296),
                            Email = "necil@necil.com",
                            Gender = true,
                            IsActive = true,
                            NickName = "necilcakmak",
                            Password = "$2a$11$wnQMJKF1vC6fAxs5IDaM1.5S3oMG.gEQMhON0bHUl5UQfe8v1AwIK",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(5302),
                            UserName = "Necil",
                            UserSurname = "Çakmak"
                        },
                        new
                        {
                            Id = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            BirthDate = new DateTime(1990, 11, 17, 22, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(5374),
                            Email = "ömer@ömer.com",
                            Gender = false,
                            IsActive = true,
                            NickName = "ömergürsoy",
                            Password = "$2a$11$uNx/XA0odP6BAp8xKqtkausOYVPqmGNmq1GYK/y0E6OgQNb/7XIfC",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(5376),
                            UserName = "Ömer",
                            UserSurname = "Gürsoy"
                        },
                        new
                        {
                            Id = new Guid("30d00d67-4f1e-405f-a992-f9ef825550c8"),
                            BirthDate = new DateTime(1985, 9, 24, 21, 0, 0, 0, DateTimeKind.Utc),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(5389),
                            Email = "server@dogan.com",
                            Gender = false,
                            IsActive = true,
                            NickName = "serverdogan",
                            Password = "$2a$11$uNx/XA0odP6BAp8xKqtkausOYVPqmGNmq1GYK/y0E6OgQNb/7XIfC",
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 565, DateTimeKind.Utc).AddTicks(5391),
                            UserName = "Server",
                            UserSurname = "Doğan"
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserFollowed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("FollowedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(3214));

                    b.Property<Guid>("FollowedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FollowedUserId");

                    b.ToTable("UserFolloweds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7cd06ada-c8ce-4d70-9764-d7fe138bdd9c"),
                            FollowedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(5200),
                            FollowedUserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c")
                        },
                        new
                        {
                            Id = new Guid("9955ae8d-c9ff-41b8-84c1-12cd18770fed"),
                            FollowedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(5211),
                            FollowedUserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908"),
                            UserId = new Guid("30d00d67-4f1e-405f-a992-f9ef825550c8")
                        },
                        new
                        {
                            Id = new Guid("e9884b3f-6665-42b4-9b67-1555ce3b4f94"),
                            FollowedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(5215),
                            FollowedUserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            UserId = new Guid("30d00d67-4f1e-405f-a992-f9ef825550c8")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserFollower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("FollowedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(5731));

                    b.Property<Guid>("FollowersUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FollowersUserId");

                    b.ToTable("UserFollowers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a07a6456-3576-48ad-8914-1cd5c1152904"),
                            FollowedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(7671),
                            FollowersUserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c"),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        },
                        new
                        {
                            Id = new Guid("1621633e-4c36-4a7e-a24c-aac0d35e4d9f"),
                            FollowedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(7682),
                            FollowersUserId = new Guid("30d00d67-4f1e-405f-a992-f9ef825550c8"),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        },
                        new
                        {
                            Id = new Guid("3e37ab15-45eb-44ee-940a-59f87b407a8c"),
                            FollowedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(7687),
                            FollowersUserId = new Guid("30d00d67-4f1e-405f-a992-f9ef825550c8"),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(741));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("NewBlog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ReceiveMail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(1026));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ff845a2-ad00-4158-8b4a-061a5764c789"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(2644),
                            IsActive = true,
                            IsApproved = true,
                            NewBlog = true,
                            ReceiveMail = true,
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(2652),
                            UserId = new Guid("c91266a4-35d3-4b60-89aa-6fa26c33c908")
                        },
                        new
                        {
                            Id = new Guid("e88c8860-4b9a-4736-9ed3-5cf23a75a86b"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(2657),
                            IsActive = true,
                            IsApproved = false,
                            NewBlog = true,
                            ReceiveMail = true,
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(2659),
                            UserId = new Guid("45b533cd-ed21-4eb7-bb90-8838b6f9486c")
                        },
                        new
                        {
                            Id = new Guid("a6bacb41-6666-4f2c-b5c8-afdac80f2026"),
                            CreatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(2662),
                            IsActive = true,
                            IsApproved = true,
                            NewBlog = true,
                            ReceiveMail = true,
                            UpdatedDate = new DateTime(2022, 3, 18, 10, 57, 9, 566, DateTimeKind.Utc).AddTicks(2664),
                            UserId = new Guid("30d00d67-4f1e-405f-a992-f9ef825550c8")
                        });
                });

            modelBuilder.Entity("Blog.Entities.Entities.Article", b =>
                {
                    b.HasOne("Blog.Entities.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Category", b =>
                {
                    b.HasOne("Blog.Entities.Entities.MainCategory", "MainCategory")
                        .WithMany("Categories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Comment", b =>
                {
                    b.HasOne("Blog.Entities.Entities.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserFollowed", b =>
                {
                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany("UserFollowed")
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserFollower", b =>
                {
                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithMany("UserFollowers")
                        .HasForeignKey("FollowersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.UserSetting", b =>
                {
                    b.HasOne("Blog.Entities.Entities.User", "User")
                        .WithOne("UserSetting")
                        .HasForeignKey("Blog.Entities.Entities.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Blog.Entities.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Blog.Entities.Entities.MainCategory", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Blog.Entities.Entities.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("UserFollowed");

                    b.Navigation("UserFollowers");

                    b.Navigation("UserSetting")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
